name: Build Spring WAR

on:
  push:
    branches:
      - devpanic

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload WAR as artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: target/*.war